######################################################################
# Automatically generated by qmake (2.01a) Mon Jun 27 13:50:47 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += interact.h pedro_connection.h qpconfig.h xqpdebug.h ../tcp_qp.h ../errors.h
SOURCES += interact.cc main.cc pedro_connection.cc qpconfig.cc xqpdebug.cc ../tcp.cc ../errors.cc
