.\" Copyright (c) Software Verification Research Centre - All Rights Reserved.
.TH qecat 1 "1 March 2000" SVRC
.SH NAME
qecat \- Decoder for byte-encoded Qu-Prolog files.
.SH SYNOPSIS
.B qecat
.BI input
.SH DESCRIPTION
\f4qecat\f1 is the decoder for byte-encoded Qu-Prolog files. 
It reads the byte-encoded file from \f4input\f1 and writes plain text
to standard output.
.SH OPTIONS
.TP
.BI input
Input file for the decoder.
.SH SEE ALSO
.BR qc (1).
.SH COPYRIGHT
Software Verification Research Centre, The
University of Queensland, Australia 4072.
