######################################################################
# Automatically generated by qmake (1.04a) Thu May 6 09:02:14 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += interact.h qpconfig.h qthelp.h term.h xqp.h xqpqueries.h
SOURCES += interact.cc \
           main.cc \
           qpconfig.cc \
           qthelp.cc \
           term.cc \
           xqp.cc \
           xqpqueries.cc
